<?php

namespace Database\Seeders;

use App\Models\Guest;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GuestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Guest list from provided data
        $guests = [
            ['name' => 'Kholik & Istri', 'isVIP' => true],
            ['name' => 'Aditya Suryansah', 'isVIP' => false],
            ['name' => 'Adri', 'isVIP' => false],
            ['name' => 'Ale', 'isVIP' => true],
            ['name' => 'Alwiantara', 'isVIP' => false],
            ['name' => 'Arya & Ayu', 'isVIP' => true],
            ['name' => 'Atik & Suami', 'isVIP' => true],
            ['name' => 'Bayu Sukma Maulana', 'isVIP' => true],
            ['name' => 'Khuncoro Ari Webowo', 'isVIP' => true],
            ['name' => 'Dewi Fortuna & Suami', 'isVIP' => true],
            ['name' => 'Cikara Enggartiasti', 'isVIP' => true],
            ['name' => 'Eni', 'isVIP' => false],
            ['name' => 'Nenden', 'isVIP' => false],
            ['name' => 'Cita Suci Saputri', 'isVIP' => false],
            ['name' => 'Dania', 'isVIP' => true],
            ['name' => 'Haikal Husein', 'isVIP' => true],
            ['name' => 'Dimas Purnomo', 'isVIP' => false],
            ['name' => 'Dimas Kunto Aji', 'isVIP' => true],
            ['name' => 'Erda Octarianti', 'isVIP' => false],
            ['name' => 'Nadia Sabila', 'isVIP' => false],
            ['name' => 'Fiqky Ilham', 'isVIP' => false],
            ['name' => 'Gema Nur', 'isVIP' => false],
            ['name' => 'Gustian Herlambang', 'isVIP' => false],
            ['name' => 'Herlangga', 'isVIP' => false],
            ['name' => 'Herwin Maulana', 'isVIP' => false],
            ['name' => 'Hilal Dhafir A', 'isVIP' => true],
            ['name' => 'Hilman Naufal', 'isVIP' => false],
            ['name' => 'Idrus', 'isVIP' => false],
            ['name' => 'Ismail Marzuki', 'isVIP' => false],
            ['name' => 'Raply Khatami', 'isVIP' => false],
            ['name' => 'Juniver', 'isVIP' => false],
            ['name' => 'Miftah Irfan Basuki', 'isVIP' => false],
            ['name' => 'Fikri & Istri', 'isVIP' => true],
            ['name' => 'M Rizki W', 'isVIP' => false],
            ['name' => 'Ratu Syahla', 'isVIP' => false],
            ['name' => 'Maulana & Istri', 'isVIP' => true],
            ['name' => 'Mega Atikadevi', 'isVIP' => false],
            ['name' => 'Komang Puspa Yoga', 'isVIP' => true],
            ['name' => 'Nuning', 'isVIP' => false],
            ['name' => 'M Fauzan', 'isVIP' => false],
            ['name' => 'Pahmi Alifya', 'isVIP' => false],
            ['name' => 'Haura Wiyana', 'isVIP' => false],
            ['name' => 'Reza', 'isVIP' => false],
            ['name' => 'Ricky Wahyudi', 'isVIP' => true],
            ['name' => 'Riris', 'isVIP' => false],
            ['name' => 'Runanto', 'isVIP' => true],
            ['name' => 'Shandy Zolla', 'isVIP' => true],
            ['name' => 'Sigit Widodo', 'isVIP' => false],
            ['name' => 'Agis', 'isVIP' => false],
            ['name' => 'Irfani', 'isVIP' => false],
            ['name' => 'Arssy', 'isVIP' => true],
            ['name' => 'Bu Dahlia', 'isVIP' => false],
            ['name' => 'Bu Desy', 'isVIP' => false],
            ['name' => 'Arvhidia', 'isVIP' => false],
            ['name' => 'Dea', 'isVIP' => false],
            ['name' => 'Debby', 'isVIP' => true],
            ['name' => 'Fahri', 'isVIP' => false],
            ['name' => 'Dimas IT', 'isVIP' => false],
            ['name' => 'Fadil Gunawan', 'isVIP' => false],
            ['name' => 'Fahmi Maulana', 'isVIP' => false],
            ['name' => 'Gesa', 'isVIP' => false],
            ['name' => 'Hardiansyah', 'isVIP' => false],
            ['name' => 'Mba Yuni', 'isVIP' => false],
            ['name' => 'Pak Deni', 'isVIP' => false],
            ['name' => 'Pak Haja', 'isVIP' => false],
            ['name' => 'Pak Ipul', 'isVIP' => false],
            ['name' => 'Pak Mukhlisin', 'isVIP' => false],
            ['name' => 'Pak Taufik Produksi', 'isVIP' => false],
            ['name' => 'Pak Taufik TS', 'isVIP' => false],
            ['name' => 'Pak Tri', 'isVIP' => false],
            ['name' => 'Pungki', 'isVIP' => false],
            ['name' => 'Raka & Istri', 'isVIP' => true],
            ['name' => 'Reni & Suami', 'isVIP' => true],
            ['name' => 'Silvi', 'isVIP' => false],
            ['name' => 'Thomas Ardi', 'isVIP' => false],
            ['name' => 'Bu Rustini', 'isVIP' => false],
            ['name' => 'Pak Maurice Adema', 'isVIP' => false],
            ['name' => 'Stanley Adema', 'isVIP' => false],
            ['name' => 'Mbak Wiwin', 'isVIP' => false],
            ['name' => 'Mbak Marta', 'isVIP' => false],
            ['name' => 'Mbak Imas', 'isVIP' => false],
            ['name' => 'Widi Affandi', 'isVIP' => false],
            ['name' => 'Tomi Aditya', 'isVIP' => false],
            ['name' => 'Rosul', 'isVIP' => false],
            ['name' => 'Pak Agus', 'isVIP' => false],
            ['name' => 'Tasya', 'isVIP' => false],
            ['name' => 'Bu Nana', 'isVIP' => false],
            ['name' => 'Syifa Hilya', 'isVIP' => false],
            ['name' => 'Teguh', 'isVIP' => false],
            ['name' => 'Unggul Sulaiman', 'isVIP' => true],
            ['name' => 'Frillya', 'isVIP' => false],
            ['name' => 'Wahyu Dwi Prasetyo', 'isVIP' => true],
            ['name' => 'Wiendra', 'isVIP' => false],
            ['name' => 'Wildan Diaspratama', 'isVIP' => true],
            ['name' => 'Hadyan Adam', 'isVIP' => true],
            ['name' => 'Dicky Mahfudin', 'isVIP' => true],
            ['name' => 'Ado', 'isVIP' => true],
            ['name' => 'Hafiz', 'isVIP' => true],
            ['name' => 'Pak Andi Chairunnas', 'isVIP' => true],
            ['name' => 'Ali', 'isVIP' => false],
            ['name' => 'Amanda', 'isVIP' => false],
            ['name' => 'Joe Fachrizal', 'isVIP' => true],
            ['name' => 'Triyoga Ginanjar', 'isVIP' => true],
            ['name' => 'Ahmad Dimas Permadi', 'isVIP' => true],
            ['name' => 'Bukhori Muslim', 'isVIP' => true],
            ['name' => 'Denny', 'isVIP' => false],
            ['name' => 'Dinda', 'isVIP' => false],
            ['name' => 'Angga', 'isVIP' => false],
            ['name' => 'Dwi Kumis', 'isVIP' => false],
            ['name' => 'Gozali', 'isVIP' => true],
            ['name' => 'Irham', 'isVIP' => false],
            ['name' => 'Nopi', 'isVIP' => false],
            ['name' => 'Kobex', 'isVIP' => false],
            ['name' => 'Naya Nurwiyoga', 'isVIP' => true],
            ['name' => 'Rama', 'isVIP' => false],
            ['name' => 'Sella', 'isVIP' => false],
            ['name' => 'Sigit', 'isVIP' => false],
            ['name' => 'Endah Putri', 'isVIP' => false],
            ['name' => 'Novinda N', 'isVIP' => false],
            ['name' => 'Bimo MR', 'isVIP' => false],
            ['name' => 'Arif Rahman', 'isVIP' => false],
            ['name' => 'Euis', 'isVIP' => false],
            ['name' => 'Lutfi', 'isVIP' => false],
            ['name' => 'Agung Ardiansyah', 'isVIP' => false],
            ['name' => 'Surya Prayoga', 'isVIP' => false],
            ['name' => 'Fahmi Izzul', 'isVIP' => false],
            ['name' => 'Nurmalita', 'isVIP' => false],
            ['name' => 'Cindy Maya', 'isVIP' => false],
            ['name' => 'Farhan Abdillah', 'isVIP' => false],
        ];

        foreach ($guests as $guestData) {
            // Generate a unique URL based on the guest's name
            $slug = strtolower(str_replace([' ', '&'], ['-', 'and'], $guestData['name']));
            $url = "https://wedding-invitation.com/?to={$slug}";

            Guest::create([
                'wedding_id'        => 1,
                'name'              => $guestData['name'],
                'isVIP'             => $guestData['isVIP'],
                'url'               => $url,
                'created_at'        => now(),
                'updated_at'        => now()
            ]);
        }
    }
}
