<?php

namespace Database\Seeders;

use App\Models\Guest;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GuestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Guest list from provided data
        $guests = [
            ['name' => 'Aditya Suryansah', 'isVIP' => false],
            ['name' => 'Adri', 'isVIP' => false],
            ['name' => 'Alwiantara & Istri', 'isVIP' => false],
            ['name' => 'Khuncoro Ari Webowo', 'isVIP' => true],
            ['name' => 'Dewi Fortuna & Suami', 'isVIP' => true],
            ['name' => 'Dimas Kunto Aji', 'isVIP' => true],
            ['name' => 'Fiqky Ilham', 'isVIP' => false],
            ['name' => 'Herlangga', 'isVIP' => false],
            ['name' => 'Hilal Dhafir A', 'isVIP' => true],
            ['name' => 'Maulana & Istri', 'isVIP' => true],
            ['name' => 'M Fauzan', 'isVIP' => false],
            ['name' => 'Reza', 'isVIP' => false],
            ['name' => 'Ricky Wahyudi', 'isVIP' => true],
            ['name' => 'Runanto', 'isVIP' => true],
            ['name' => 'Shandy Zolla', 'isVIP' => true],
            ['name' => 'Sigit Widodo', 'isVIP' => false],
            ['name' => 'Wiendra', 'isVIP' => false],
            ['name' => 'Wildan Diaspratama', 'isVIP' => true],
            ['name' => 'Lutfi', 'isVIP' => false],
            ['name' => 'Agung Ardiansyah', 'isVIP' => false],
            ['name' => 'Surya Prayoga', 'isVIP' => false],
            ['name' => 'Fahmi Izzul', 'isVIP' => false],
            ['name' => 'Idrus', 'isVIP' => false],
            ['name' => 'Ismail Marzuki', 'isVIP' => false],
            ['name' => 'Raply Khatami', 'isVIP' => false],
            ['name' => 'Miftah Irfan Basuki', 'isVIP' => false],
            ['name' => 'Fikri & Istri', 'isVIP' => true],
            ['name' => 'Teguh & Istri', 'isVIP' => false],
            ['name' => 'Kholik & Istri', 'isVIP' => true],
            ['name' => 'Haikal Husein', 'isVIP' => true],
            ['name' => 'Unggul Sulaiman', 'isVIP' => true],
            ['name' => 'Wahyu Dwi Prasetyo', 'isVIP' => true],
            ['name' => 'Ale', 'isVIP' => true],
            ['name' => 'Arya & Istri', 'isVIP' => true],
            ['name' => 'Bayu Sukma Maulana', 'isVIP' => true],
            ['name' => 'Dania', 'isVIP' => true],
            ['name' => 'Herwin Maulana', 'isVIP' => false],
            ['name' => 'Nuning', 'isVIP' => false],
            ['name' => 'Cikara Enggartiasti', 'isVIP' => true],
            ['name' => 'Eni', 'isVIP' => false],
            ['name' => 'Nenden', 'isVIP' => false],
            ['name' => 'Agis & Istri', 'isVIP' => false],
            ['name' => 'Arvhidia', 'isVIP' => false],
            ['name' => 'Debby', 'isVIP' => true],
            ['name' => 'Thomas Ardi', 'isVIP' => false],
            ['name' => 'Widi Affandi', 'isVIP' => false],
            ['name' => 'Cita Suci Saputri', 'isVIP' => false],
            ['name' => 'Erda Octarianti', 'isVIP' => false],
            ['name' => 'Nadia Sabila', 'isVIP' => false],
            ['name' => 'Gema Nur', 'isVIP' => false],
            ['name' => 'Gustian Herlambang', 'isVIP' => false],
            ['name' => 'Hilman Naufal', 'isVIP' => false],
            ['name' => 'Juniver', 'isVIP' => false],
            ['name' => 'M Rizki W', 'isVIP' => false],
            ['name' => 'Ratu Syahla', 'isVIP' => false],
            ['name' => 'Pahmi Alifya & Istri', 'isVIP' => false],
            ['name' => 'Riris', 'isVIP' => false],
            ['name' => 'Syifa Hilya', 'isVIP' => false],
            ['name' => 'Frillya', 'isVIP' => false],
            ['name' => 'Euis Wida & Suami', 'isVIP' => false],
            ['name' => 'Atik & Suami', 'isVIP' => true],
            ['name' => 'Naya Nurwiyoga', 'isVIP' => true],
            ['name' => 'Mega Atikadevi', 'isVIP' => false],
            ['name' => 'Komang Puspa Yoga', 'isVIP' => true],
            ['name' => 'Hadyan Adam & Istri', 'isVIP' => true],
            ['name' => 'Dicky Mahfudin & Istri', 'isVIP' => true],
            ['name' => 'Ado', 'isVIP' => true],
            ['name' => 'Hapis', 'isVIP' => true],
            ['name' => 'Ali', 'isVIP' => false],
            ['name' => 'Amanda', 'isVIP' => false],
            ['name' => 'Triyoga Ginanjar & Istri', 'isVIP' => true],
            ['name' => 'Ahmad Dimas & Istri', 'isVIP' => true],
            ['name' => 'Bukhori Muslim', 'isVIP' => true],
            ['name' => 'Denny', 'isVIP' => false],
            ['name' => 'Angga', 'isVIP' => false],
            ['name' => 'Dwi Kumis', 'isVIP' => false],
            ['name' => 'Irham', 'isVIP' => false],
            ['name' => 'Novia Ernawati', 'isVIP' => false],
            ['name' => 'Rama', 'isVIP' => false],
            ['name' => 'Sella', 'isVIP' => false],
            ['name' => 'Sigit', 'isVIP' => false],
            ['name' => 'Endah Putri & Suami', 'isVIP' => false],
            ['name' => 'Novinda & Suami', 'isVIP' => false],
            ['name' => 'Arif Rahman', 'isVIP' => false],
            ['name' => 'Nurmalita', 'isVIP' => false],
            ['name' => 'Cindy Maya & Suami', 'isVIP' => false],
            ['name' => 'Farhan Abdillah', 'isVIP' => false],
            ['name' => 'Purnama (Empuh) & Istri', 'isVIP' => false],
            ['name' => 'Arssy', 'isVIP' => true],
            ['name' => 'Bu Dahlia', 'isVIP' => false],
            ['name' => 'Bu Desy', 'isVIP' => false],
            ['name' => 'Dea', 'isVIP' => false],
            ['name' => 'Fahri', 'isVIP' => false],
            ['name' => 'Dimas IT', 'isVIP' => false],
            ['name' => 'Fadil Gunawan', 'isVIP' => false],
            ['name' => 'Fahmi Maulana', 'isVIP' => false],
            ['name' => 'Gesa', 'isVIP' => false],
            ['name' => 'Hardiansyah', 'isVIP' => false],
            ['name' => 'Mba Yuni', 'isVIP' => false],
            ['name' => 'Pak Deni', 'isVIP' => false],
            ['name' => 'Pak Haja', 'isVIP' => false],
            ['name' => 'Pak Ipul', 'isVIP' => false],
            ['name' => 'Pak Mukhlisin', 'isVIP' => false],
            ['name' => 'Pak Taufik Produksi', 'isVIP' => false],
            ['name' => 'Pak Taufik TS', 'isVIP' => false],
            ['name' => 'Pak Tri', 'isVIP' => false],
            ['name' => 'Pungki', 'isVIP' => false],
            ['name' => 'Raka & Istri', 'isVIP' => true],
            ['name' => 'Reni & Suami', 'isVIP' => true],
            ['name' => 'Silvi', 'isVIP' => false],
            ['name' => 'Stanley Adema', 'isVIP' => false],
            ['name' => 'Bu Rustini', 'isVIP' => false],
            ['name' => 'Pak Maurice Adema', 'isVIP' => false],
            ['name' => 'Pak Termidzi', 'isVIP' => false],
            ['name' => 'Pak Maylon', 'isVIP' => false],
            ['name' => 'Mba Wiwin', 'isVIP' => false],
            ['name' => 'Mba Marta', 'isVIP' => false],
            ['name' => 'Mba Imas', 'isVIP' => false],
            ['name' => 'Tomi Aditya', 'isVIP' => false],
            ['name' => 'Rosul', 'isVIP' => false],
            ['name' => 'Pak Agus', 'isVIP' => false],
            ['name' => 'Tasya', 'isVIP' => false],
            ['name' => 'Bu Nana', 'isVIP' => false],
            ['name' => 'Pak Joni', 'isVIP' => false],
            ['name' => 'Teh Uca', 'isVIP' => false],
            ['name' => 'Dimas Purnomo', 'isVIP' => false],
            ['name' => 'Pak Andi Chairunnas', 'isVIP' => true],
            ['name' => 'Joe Fachrizal', 'isVIP' => true],
            ['name' => 'Dinda', 'isVIP' => false],
            ['name' => 'Gozali & Istri', 'isVIP' => true],
            ['name' => 'Kobex & Istri', 'isVIP' => false],
            ['name' => 'Afwan Yusuf', 'isVIP' => false],
            ['name' => 'Kak Dhanty', 'isVIP' => false],
            ['name' => 'Rahma Simamora', 'isVIP' => false],
            ['name' => 'Safitri', 'isVIP' => false],
            ['name' => 'Umam', 'isVIP' => false],
            ['name' => 'Alfo', 'isVIP' => false],
            ['name' => 'Bagol', 'isVIP' => false],
            ['name' => 'Daffa', 'isVIP' => false],
            ['name' => 'Ipoel Lolo', 'isVIP' => false],
            ['name' => 'Bang Fei', 'isVIP' => false],
            ['name' => 'Izza', 'isVIP' => false],
            ['name' => 'Chintya', 'isVIP' => false],
            ['name' => 'Rama', 'isVIP' => false],
            ['name' => 'Indah', 'isVIP' => false],
            ['name' => 'Tiara', 'isVIP' => false],
            ['name' => 'Salsa', 'isVIP' => false],
            ['name' => 'Ka Gadis', 'isVIP' => false],
            ['name' => 'Annita', 'isVIP' => false],
            ['name' => 'Teh Fitri & Suami', 'isVIP' => false],
            ['name' => 'Ka Indah', 'isVIP' => false],
            ['name' => 'Ka Lulu', 'isVIP' => false],
            ['name' => 'Cicay', 'isVIP' => false],
            ['name' => 'Eni', 'isVIP' => false],
            ['name' => 'Celine', 'isVIP' => false],
            ['name' => 'Saskia', 'isVIP' => false],
            ['name' => 'Ka Silvih', 'isVIP' => false],
            ['name' => 'Erwin', 'isVIP' => false],
            ['name' => 'Pak Hengky', 'isVIP' => true],
            ['name' => 'Bu Cindy', 'isVIP' => true],
            ['name' => 'Ojan', 'isVIP' => false],
            ['name' => 'Nana', 'isVIP' => false],
            ['name' => 'Icut', 'isVIP' => true],
            ['name' => 'Wilda', 'isVIP' => true],
            ['name' => 'Dilla', 'isVIP' => true],
            ['name' => 'Wulan', 'isVIP' => false],
            ['name' => 'Febi', 'isVIP' => false],
            ['name' => 'Ka Erni', 'isVIP' => false],
            ['name' => 'Rasna', 'isVIP' => false],
            ['name' => 'Almas', 'isVIP' => false],
            ['name' => 'Haura', 'isVIP' => false],
            ['name' => 'Hesti', 'isVIP' => false],
            ['name' => 'Ka Silvi RF', 'isVIP' => false],
            ['name' => 'Seyy & Haruto', 'isVIP' => false],
            ['name' => 'Nafida & Hyunsuk', 'isVIP' => false],
            ['name' => 'Fahri Medilansyah', 'isVIP' => false],
            ['name' => 'Rahmat Diki', 'isVIP' => false],
            ['name' => 'Awaluya', 'isVIP' => false],
            ['name' => 'Ilham', 'isVIP' => false],
            ['name' => 'Ka Meditia', 'isVIP' => false],
            ['name' => 'Ka Sintha', 'isVIP' => false],
            ['name' => 'Asep', 'isVIP' => false],
            ['name' => 'Ka Via', 'isVIP' => false],
            ['name' => 'Ka Joo', 'isVIP' => false],
            ['name' => 'Ka Cindy', 'isVIP' => false],
            ['name' => 'Ka Yorin', 'isVIP' => false],
            ['name' => '99\'s', 'isVIP' => false],
            ['name' => 'Nineties', 'isVIP' => false],
            ['name' => 'Ihsan', 'isVIP' => false],
            ['name' => 'Babar', 'isVIP' => false],
            ['name' => 'Reza', 'isVIP' => false],
            ['name' => 'Rizky', 'isVIP' => false],
            ['name' => 'Agung', 'isVIP' => false],
            ['name' => 'Nadhira', 'isVIP' => false],
            ['name' => 'Nabila', 'isVIP' => false],
            ['name' => 'Athiyyah', 'isVIP' => false],
            ['name' => 'Indri', 'isVIP' => false],
            ['name' => 'Riska & Suami', 'isVIP' => true],
            ['name' => 'April', 'isVIP' => true],
            ['name' => 'Tasem', 'isVIP' => true],
            ['name' => 'Basir', 'isVIP' => true],
            ['name' => 'Daffa', 'isVIP' => true],
            ['name' => 'Rizal Priatna', 'isVIP' => false],
            ['name' => 'Nurul', 'isVIP' => false],
            ['name' => 'Clarisa', 'isVIP' => false],
            ['name' => 'Dinda', 'isVIP' => false],
            ['name' => 'Mycco', 'isVIP' => false],
            ['name' => 'Asep', 'isVIP' => false],
            ['name' => 'Diar Risna', 'isVIP' => false],
            ['name' => 'Suranti Devi', 'isVIP' => false],
            ['name' => 'Pascal', 'isVIP' => false],
            ['name' => 'Eha', 'isVIP' => false],
            ['name' => 'Windy', 'isVIP' => false],
            ['name' => 'Haryani', 'isVIP' => false],
            ['name' => 'Sisy', 'isVIP' => false],
            ['name' => 'Hera', 'isVIP' => false],
            ['name' => 'Dian Azizah', 'isVIP' => false],
            ['name' => 'Zelind', 'isVIP' => false],
            ['name' => 'Leony', 'isVIP' => false],
            ['name' => 'Alya', 'isVIP' => false],
            ['name' => 'Desti', 'isVIP' => false],
            ['name' => 'Afifah & Supri', 'isVIP' => false],
            ['name' => 'Ka Zahra & Suami', 'isVIP' => false],
            ['name' => 'Dini & Faiz', 'isVIP' => false],
            ['name' => 'Alfina', 'isVIP' => false],
            ['name' => 'Cindy & Suami', 'isVIP' => false],
            ['name' => 'Sherly', 'isVIP' => false],
            ['name' => 'Sisca Camelia', 'isVIP' => false],
            ['name' => 'Kiki Maryati', 'isVIP' => false],
            ['name' => 'Herdiana Dewi', 'isVIP' => false],
            ['name' => 'Yuyun Suryani', 'isVIP' => false],
            ['name' => 'Diah & Ridwan', 'isVIP' => false],
            ['name' => 'Biah & Rico', 'isVIP' => false],
            ['name' => 'Amartia & Ridwan', 'isVIP' => false],
            ['name' => 'Ikhsan', 'isVIP' => false],
            ['name' => 'Riva\'i', 'isVIP' => false],
            ['name' => 'Devi', 'isVIP' => false],
            ['name' => 'Iin', 'isVIP' => false],
            ['name' => 'Bang Imam', 'isVIP' => false],
            ['name' => 'Cacha', 'isVIP' => false],
            ['name' => 'Aldi Bunawan', 'isVIP' => false],
            ['name' => 'Ka Zudin', 'isVIP' => false],
            ['name' => 'Ka Reza', 'isVIP' => false],
            ['name' => 'Ka Gufron', 'isVIP' => false],
            ['name' => 'Ka Andri', 'isVIP' => false],
            ['name' => 'Ka Teguh', 'isVIP' => false],
            ['name' => 'Ka Deni', 'isVIP' => false],
            ['name' => 'Ka Eti & Ka Acep', 'isVIP' => false],
            ['name' => 'Ka STM', 'isVIP' => false],
            ['name' => 'Ka Nasrun', 'isVIP' => false],
            ['name' => 'Ka Asep', 'isVIP' => false],
            ['name' => 'Pak Heru', 'isVIP' => true],
            ['name' => 'Pak Cecep', 'isVIP' => true],
            ['name' => 'Pak Ruslan', 'isVIP' => true],
            ['name' => 'Ka Kamal', 'isVIP' => false],
            ['name' => 'Alif Huda', 'isVIP' => false],
            ['name' => 'Ranto', 'isVIP' => false],
            ['name' => 'Ka Sarta', 'isVIP' => false],
            ['name' => 'Pak David', 'isVIP' => true],
            ['name' => 'Wildan Irawan', 'isVIP' => false],
            ['name' => 'Opang', 'isVIP' => false],
            ['name' => 'Supriyadi', 'isVIP' => false],
            ['name' => 'Syifa Qolbu', 'isVIP' => false],
            ['name' => 'Ayah Sures', 'isVIP' => true],
            ['name' => 'Bang Lintang', 'isVIP' => false],
            ['name' => 'Pak H Khoerudin', 'isVIP' => true],
            ['name' => 'Pak H Jaenal', 'isVIP' => true],
            ['name' => 'Pak Suhada', 'isVIP' => true],
            ['name' => 'Pak Abdulloh', 'isVIP' => true],
            ['name' => 'Pak Darsum', 'isVIP' => true],
            ['name' => 'Pak Ikbal', 'isVIP' => true],
            ['name' => 'Pak Sigit', 'isVIP' => true],
            ['name' => 'Pak Agus', 'isVIP' => true],
            ['name' => 'Pak Kastari', 'isVIP' => true],
            ['name' => 'Pak Rudy', 'isVIP' => true],
            ['name' => 'Pak Ust Daden', 'isVIP' => true],
            ['name' => 'Pak Iin', 'isVIP' => true],
            ['name' => 'Pak Fajar', 'isVIP' => true],
            ['name' => 'Pak Ramdhan', 'isVIP' => true],
            ['name' => 'Pak Hary', 'isVIP' => true],
            ['name' => 'Coach Yeyen', 'isVIP' => true],
            ['name' => 'Pak Januar', 'isVIP' => true],
            ['name' => 'Pak Pahru', 'isVIP' => true],
            ['name' => 'Pak Iqbal', 'isVIP' => true],
            ['name' => 'Pak Sundawa', 'isVIP' => true],
            ['name' => 'Pak Rouf', 'isVIP' => true],
            ['name' => 'Pak Asep', 'isVIP' => true],
            ['name' => 'Pak Budi', 'isVIP' => true],
            ['name' => 'Pak Jaka', 'isVIP' => true],
            ['name' => 'Mang Kos', 'isVIP' => true],
            ['name' => 'Mang Ndan', 'isVIP' => true],
            ['name' => 'Saman Samin', 'isVIP' => true],
            ['name' => 'Rizki Ikok', 'isVIP' => true],
            ['name' => 'Pak Rangga', 'isVIP' => true],
            ['name' => 'Bu Hj Solihat', 'isVIP' => true],
            ['name' => 'Bu Hj Enung', 'isVIP' => true],
            ['name' => 'Juna', 'isVIP' => true],
            ['name' => 'Ayulia', 'isVIP' => true],
            ['name' => 'Bu Sri Purwati', 'isVIP' => true],
            ['name' => 'Bu Andris', 'isVIP' => true],
            ['name' => 'Bu Eka', 'isVIP' => true],
            ['name' => 'Bu Evi', 'isVIP' => true],
            ['name' => 'Bu Fitria', 'isVIP' => true],
            ['name' => 'Bu Ismi', 'isVIP' => true],
            ['name' => 'Bu Ning', 'isVIP' => true],
            ['name' => 'Bu Puti', 'isVIP' => true],
            ['name' => 'Bu Putri', 'isVIP' => true],
            ['name' => 'Bu Widya', 'isVIP' => true],
            ['name' => 'Bu Widia', 'isVIP' => true],
            ['name' => 'Bu Yati', 'isVIP' => true],
            ['name' => 'Bu Yuli', 'isVIP' => true],
            ['name' => 'Miss Atmi', 'isVIP' => true],
            ['name' => 'Miss Tria', 'isVIP' => true],
            ['name' => 'Khalifah Viani', 'isVIP' => true],
            ['name' => 'Maiya Damayanti', 'isVIP' => true],
            ['name' => 'Teh Retna', 'isVIP' => true],
            ['name' => 'Zia & Asahi', 'isVIP' => true],
            ['name' => 'Fani & Hyunsuk', 'isVIP' => true],
            ['name' => 'Oca & Hyunsuk', 'isVIP' => true],
            ['name' => 'Rin & Hyunsuk', 'isVIP' => true],
            ['name' => 'Fina & Junghwan', 'isVIP' => true],
            ['name' => 'Anisa Yuliana & Ardi', 'isVIP' => false],
            ['name' => 'Alya', 'isVIP' => false],
            ['name' => 'Arnesya', 'isVIP' => false],
            ['name' => 'Haura', 'isVIP' => false],
            ['name' => 'Desti', 'isVIP' => false],
            ['name' => 'Audi', 'isVIP' => false],
            ['name' => 'Evita', 'isVIP' => false],
            ['name' => 'Eka Yunita', 'isVIP' => false],
            ['name' => 'Neng Winda', 'isVIP' => false],
            ['name' => 'Tasya', 'isVIP' => false],
            ['name' => 'Ria', 'isVIP' => false],
            ['name' => 'Vanindya', 'isVIP' => false],
            ['name' => 'Ipen', 'isVIP' => false],
            ['name' => 'Putri', 'isVIP' => false],
            ['name' => 'Tania', 'isVIP' => false],
            ['name' => 'Maysyaroh', 'isVIP' => false],
            ['name' => 'Vera Verliana', 'isVIP' => false],
            ['name' => 'Maulia Santika', 'isVIP' => false],
            ['name' => 'Wiwin', 'isVIP' => false],
            ['name' => 'Khopipah', 'isVIP' => false],
            ['name' => 'Messi', 'isVIP' => false],
            ['name' => 'Teh Ipah', 'isVIP' => false],
            ['name' => 'Teh Titin', 'isVIP' => false],
            ['name' => 'Umi Kantin', 'isVIP' => false],
            ['name' => 'Teteh Kantin Pojok', 'isVIP' => false],
            ['name' => 'Mamanya Arumi', 'isVIP' => false],
            ['name' => 'Bapak Anshori', 'isVIP' => false],
            ['name' => 'Bapak Alex', 'isVIP' => false],
            ['name' => 'Bapak Darsono', 'isVIP' => false],
            ['name' => 'Bapak Suudin (uuk)', 'isVIP' => false],
            ['name' => 'Bapak Agus', 'isVIP' => false],
            ['name' => 'Prof. Dr. Endang Warsiki, S.T.P., M.Si.', 'isVIP' => false],
            ['name' => 'Bapak Bambang', 'isVIP' => false],
            ['name' => 'Bapak Yono Purwanto', 'isVIP' => false],
        ];

        foreach ($guests as $guestData) {
            // Generate a unique URL based on the guest's name
            $slug = strtolower(str_replace([' ', '&'], ['-', 'and'], $guestData['name']));
            $url = "https://wedding-invitation.com/?to={$slug}";

            Guest::create([
                'wedding_id'        => 1,
                'name'              => $guestData['name'],
                'isVIP'             => $guestData['isVIP'],
                'url'               => $url,
                'created_at'        => now(),
                'updated_at'        => now()
            ]);
        }
    }
}
