<?php

namespace Database\Seeders;

use App\Models\Guest;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GuestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Guest list from provided data
        $guests = [
            // Calon Pengantin Pria
            ['name' => 'Tuan Aldean Tegar Gemilang & Teh Nonput', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Crispy Cendy', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Aditya Suryansah', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Adri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Alwiantara & Istri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Khuncoro Ari Webowo', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Dewi Fortuna & Suami', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Dimas Kunto Aji', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Fiqky Ilham & Istri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Herlangga Saputra', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Hilal Dhafir A', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Maulana & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'M Fauzan', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Reza', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Ricky Wahyudi', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Runanto', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Shandy Zolla', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Sigit Widodo', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Wiendra', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Wildan Diaspratama', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Lutfi', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Agung Ardiansyah', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Surya Prayoga', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Fahmi Izzul', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Idrus', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Ismail Marzuki', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Raply Khatami', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Miftah Irfan Basuki', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Fikri & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Teguh & Istri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Kholik & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Haikal Husein', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Unggul Sulaiman', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Wahyu Dwi Prasetyo', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Ale & Catrine', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Arya & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Bayu Sukma Maulana', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Dania', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Herwin Maulana', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Nuning', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Cikara Enggartiasti', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Eni', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Nenden', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Agis & Istri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Arvhidia Khalisa', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Reni & Suami', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Raka & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Arssy', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Debby', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Thomas Ardi', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Widi Affandi', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Kamila Hulwi', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Cita Suci Saputri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Erda Octarianti', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Nadia Sabila', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Gema Nur', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Gustian Herlambang', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Hilman Naufal', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Juniver', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'M Rizki W', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Ratu Syahla', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Pahmi Alifya & Istri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Riris', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Syifa Hilya', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Frillya', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Euis Wida & Suami', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Atik & Suami', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Naya Nurwiyoga & Ayang', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Mega Atikadevi', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Komang Puspa Yoga', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Hadyan Adam & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Dicky Mahfudin & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Ado', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Hapis', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Ali', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Amanda', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Triyoga Ginanjar & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Ahmad Dimas & Istri', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Bukhori Muslim', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Denny', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Angga', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Dwi Kumis', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Irham', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Novia Ernawati', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Rama', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Sella', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Sigit', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Endah Putri & Suami', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Novinda & Suami', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Arif Rahman', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Nurmalita', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Cindy Maya & Suami', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Farhan Abdillah', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            ['name' => 'Purnama (Empuh) & Istri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Pria', 'is_sent' => 0],
            // Calon Pengantin Wanita
            ['name' => 'Afwan Yusuf', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Kak Dhanty', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Rahma Simamora', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Safitri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Umam', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Alfo', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Bagol', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Daffa', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ipoel Lolo', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Bang Fei', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Izza', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Chintya', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Rama', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Indah', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Tiara', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Salsa', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Gadis', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Annita', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Teh Fitri & Suami', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Indah', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Lulu', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Cicay', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Eni', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Celine', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Saskia', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Silvih', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Erwin', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Pak Hengky', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Bu Cindy', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ojan', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Nana', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Icut', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Wilda', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Dilla', 'isVIP' => true, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Wulan', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Febi', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Erni', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Rasna', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Almas', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Haura', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Hesti', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Silvi RF', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Seyy & Haruto', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Nafida & Hyunsuk', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Fahri Medilansyah', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Rahmat Diki', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Awaluya', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ilham', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Meditia', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Sintha', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Asep', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Via', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Joo', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Cindy', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ka Yorin', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => '99\'s', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Nineties', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Ihsan', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Babar', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Reza', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Rizky', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Agung', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Nadhira', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Nabila', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Athiyyah', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            ['name' => 'Indri', 'isVIP' => false, 'jenis_tamu' => 'Calon Pengantin Wanita', 'is_sent' => 0],
            // Keluarga Calon Pengantin Pria
            ['name' => 'Bapak Anshori', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            ['name' => 'Bapak Alex', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            ['name' => 'Bapak Darsono', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            ['name' => 'Bapak Su\'udin (uuk)', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            ['name' => 'Bapak Agus', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            ['name' => 'Prof. Dr. Endang Warsiki, S.T.P., M.Si.', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            ['name' => 'Bapak Bambang', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            ['name' => 'Bapak Yono Purwanto', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            ['name' => 'Bapak Subiono', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPP', 'is_sent' => 0],
            // Keluarga Calon Pengantin Wanita
            ['name' => 'Ir. H. Bambang Handana', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Yaya Suryana', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Kodiyah', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Murtiatun', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Suharno', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Munir', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Yuliedi', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Yaya Suryana', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Novalinda', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Komarudin', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Edra Ainiza', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Boby Setiawan', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Supriyadi', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'PAPCI GRUP', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Sukad dan Darto', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Ust. M Qodar Syahidin, M.Pd', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Putri Nefertiti', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'KH Abah Ofa Musthofa', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Keluarga Besar PURI CILEUNGSI', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Edi Khumaedi', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Muchtar Puri', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Edi Herdiana', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Abdul Basyir', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Ridwan Tailor', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
            ['name' => 'Ali Pd Ungu', 'isVIP' => false, 'jenis_tamu' => 'Keluarga CPW', 'is_sent' => 0],
        ];

        foreach ($guests as $guestData) {
            // Generate a unique URL based on the guest's name
            $slug = strtolower(str_replace([' ', '&'], ['-', 'and'], $guestData['name']));
            $url = "https://momen-bahagia.site/?to={$slug}";

            Guest::create([
                'wedding_id'        => 1,
                'name'              => $guestData['name'],
                'isVIP'             => $guestData['isVIP'],
                'jenis_tamu'        => $guestData['jenis_tamu'],
                'is_sent'           => $guestData['is_sent'],
                'url'               => $url,
                'created_at'        => now(),
                'updated_at'        => now()
            ]);
        }
    }
}
