version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"  # Map Laravel's server port
      - "5173:5173"  # Map Vite's dev server port
    volumes:
      - .:/app       # Mount the project directory into the container
      - ./vendor:/app/vendor # Ensure vendor dependencies persist
      - ./node_modules:/app/node_modules # Persist Node.js modules
    environment:
      APP_ENV: local
      APP_KEY: base64:random-app-key-placeholder
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db
    command: ["/bin/sh", "/app/docker-entrypoint.sh"]

  db:
    image: mysql:8.0
    container_name: laravel-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:22-alpine
    container_name: vite-server
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/app/public
    depends_on:
      - app
      - node

volumes:
  db_data:
